### ISSUE TITLE
An error when running preprocess_IPA.py

### ISSUE THREAD

**Issue by wangcongcong123** [JRC1995/Tweet-Disaster-Keyphrase#1]
$ python preprocess_IPA.py
WARNING:root:lex_lookup (from flite) is not installed.
Traceback (most recent call last):
  File "preprocess_IPA.py", line 88, in <module>
    word2ipa_vec[word], word2phono_vec[word] = word2ipa_phono_vec(word)
  File "preprocess_IPA.py", line 55, in word2ipa_phono_vec
    ipa_word = epi.trans_list(word)
  File "/home/congcong/myvenv/lib/python3.7/site-packages/epitran/_epitran.py", line 89, in trans_list
    return self.ft.segs_safe(self.epi.transliterate(word, normpunc, ligatures))
  File "/home/congcong/myvenv/lib/python3.7/site-packages/epitran/flite.py", line 94, in transliterate
    acc.append(self.english_g2p(chunk))
  File "/home/congcong/myvenv/lib/python3.7/site-packages/epitran/flite.py", line 212, in english_g2p
    arpa_text = arpa_text.splitlines()[0]
IndexError: list index out of range

**Comment by JRC1995** [comment]
Seems like an issue with Epitran. 
Try to check this section: https://github.com/dmort27/epitran#installation-of-flite-for-english-g2p
You may need to set up flite, lex_lookup to use Epitran with English properly.
